using System.Globalization;

namespace qr2l.Core;

/// <summary>
///     Localizzazione della GUI: dizionario incorporato, rilevamento automatico dalla lingua di Windows
///     e persistenza della scelta manuale dell'utente.
/// </summary>
public static class Localization
{
    #region Constants and Fields

    private const string DefaultLanguage = "en";
    private const string SettingsKey = "language";

    private static readonly Dictionary<string, string> languageNames = new() {
        ["en"] = "English",
        ["it"] = "Italiano",
        ["es"] = "Español",
        ["fr"] = "Français",
        ["de"] = "Deutsch",
        ["pt"] = "Português",
        ["ru"] = "Русский",
        ["zh"] = "中文",
        ["ja"] = "日本語",
        ["ko"] = "한국어"
    };

    private static readonly Dictionary<string, Dictionary<string, string>> strings = new() {
        ["en"] = new Dictionary<string, string> {
            ["tip_save"] = "Save the QR Code",
            ["tip_copy_image"] = "Copy image to clipboard",
            ["tip_copy_svg"] = "Copy SVG string to clipboard",
            ["tip_donate"] = "Buy me a coffee",
            ["tip_help"] = "Help",
            ["tip_language"] = "Language",
            ["tip_theme"] = "Toggle theme",
            ["tip_mode"] = "Content type: click to change",
            ["mode_auto"] = "Automatic",
            ["mode_text"] = "Text",
            ["invalid_content"] = "This text doesn't fit the selected content type",
            ["wifi_ssid"] = "Network name",
            ["wifi_password"] = "Password (empty for an open network)",
            ["wifi_security"] = "Security",
            ["wifi_hidden"] = "Hidden network",
            ["tip_form"] = "Show or hide the form",
            ["tip_form_none"] = "This content type has no form",
            ["mail_address"] = "Email address",
            ["mail_subject"] = "Subject",
            ["field_message"] = "Message",
            ["field_phone"] = "Phone number",
            ["field_intl_phone"] = "Number with country code",
            ["contact_first"] = "First name",
            ["contact_last"] = "Last name",
            ["contact_phone"] = "Phone",
            ["contact_email"] = "Email",
            ["contact_org"] = "Company",
            ["contact_web"] = "Website",
            ["event_title"] = "Title",
            ["event_location"] = "Location",
            ["event_description"] = "Description",
            ["event_all_day"] = "All day",
            ["event_start"] = "Start",
            ["event_end"] = "End",
            ["help_intro"] = "Type or paste text, a link, an email or a number: the code updates as you type. The content type is detected automatically; to choose it yourself, use the bar at the bottom.",
            ["help_examples"] = "Examples",
            ["help_guide"] = "Full guide",
            ["ph_mail"] = "email;subject;message",
            ["ph_phone"] = "phone number",
            ["ph_sms"] = "number;message",
            ["ph_whatsapp"] = "+international number;message",
            ["ph_geo"] = "latitude,longitude",
            ["ph_contact"] = "first name;last name;phone;email",
            ["ph_event"] = "title;description;location;start;end",
            ["tip_repo"] = "Open the project repository",
            ["tip_fg"] = "Sets the pixel color",
            ["tip_bg"] = "Sets the background color",
            ["color_code"] = "Code",
            ["color_background"] = "Background",
            ["tip_text"] = "Insert here the text for the QR Code",
            ["tip_picture"] = "Right click the image for options",
            ["placeholder"] = "Insert here the text for the QR Code",
            ["waiting"] = "Waiting for input...",
            ["logo_set"] = "Set the logo",
            ["logo_remove"] = "Remove the logo",
            ["menu_save_as"] = "Save As",
            ["menu_copy_image"] = "Copy As Image",
            ["menu_copy_svg"] = "Copy As SVG",
            ["dlg_save_as"] = "Save As",
            ["dlg_image_files"] = "Image files",
            ["err_title"] = "Error",
            ["err_copy_image"] = "Error copying image to clipboard:",
            ["err_copy_svg"] = "Error copying SVG to clipboard:",
            ["err_no_text"] = "Please enter text to generate QR code.",
            ["err_export"] = "Error exporting",
            ["err_open_url"] = "Cannot open the url.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "Email",
            ["fmt_phone"] = "Phone",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Geolocation",
            ["fmt_contact"] = "Contact",
            ["fmt_event"] = "Event",
        },
        ["it"] = new Dictionary<string, string> {
            ["tip_save"] = "Salva il QR Code",
            ["tip_copy_image"] = "Copia l'immagine negli appunti",
            ["tip_copy_svg"] = "Copia il codice SVG negli appunti",
            ["tip_donate"] = "Offrimi un caffè",
            ["tip_help"] = "Aiuto",
            ["tip_language"] = "Lingua",
            ["tip_theme"] = "Cambia tema",
            ["tip_mode"] = "Tipo di contenuto: clicca per cambiarlo",
            ["mode_auto"] = "Automatico",
            ["mode_text"] = "Testo",
            ["invalid_content"] = "Il testo non è adatto al tipo di contenuto scelto",
            ["wifi_ssid"] = "Nome della rete",
            ["wifi_password"] = "Password (vuota se la rete è aperta)",
            ["wifi_security"] = "Protezione",
            ["wifi_hidden"] = "Rete nascosta",
            ["tip_form"] = "Mostra o nascondi il modulo",
            ["tip_form_none"] = "Questo tipo di contenuto non ha un modulo",
            ["mail_address"] = "Indirizzo email",
            ["mail_subject"] = "Oggetto",
            ["field_message"] = "Messaggio",
            ["field_phone"] = "Numero di telefono",
            ["field_intl_phone"] = "Numero con prefisso internazionale",
            ["contact_first"] = "Nome",
            ["contact_last"] = "Cognome",
            ["contact_phone"] = "Telefono",
            ["contact_email"] = "Email",
            ["contact_org"] = "Azienda",
            ["contact_web"] = "Sito web",
            ["event_title"] = "Titolo",
            ["event_location"] = "Luogo",
            ["event_description"] = "Descrizione",
            ["event_all_day"] = "Tutto il giorno",
            ["event_start"] = "Inizio",
            ["event_end"] = "Fine",
            ["help_intro"] = "Scrivi o incolla testo, un link, un'email o un numero: il codice si aggiorna mentre scrivi. Il tipo di contenuto viene riconosciuto da solo; per sceglierlo tu, usa la barra in basso.",
            ["help_examples"] = "Esempi",
            ["help_guide"] = "Guida completa",
            ["ph_mail"] = "email;oggetto;messaggio",
            ["ph_phone"] = "numero di telefono",
            ["ph_sms"] = "numero;messaggio",
            ["ph_whatsapp"] = "+numero internazionale;messaggio",
            ["ph_geo"] = "latitudine,longitudine",
            ["ph_contact"] = "nome;cognome;telefono;email",
            ["ph_event"] = "titolo;descrizione;luogo;inizio;fine",
            ["tip_repo"] = "Apri il repository del progetto",
            ["tip_fg"] = "Imposta il colore dei pixel",
            ["tip_bg"] = "Imposta il colore di sfondo",
            ["color_code"] = "Codice",
            ["color_background"] = "Sfondo",
            ["tip_text"] = "Inserisci qui il testo per il QR Code",
            ["tip_picture"] = "Clicca con il tasto destro sull'immagine per le opzioni",
            ["placeholder"] = "Inserisci qui il testo per il QR Code",
            ["waiting"] = "In attesa di input...",
            ["logo_set"] = "Inserisci il logo",
            ["logo_remove"] = "Rimuovi il logo",
            ["menu_save_as"] = "Salva con nome",
            ["menu_copy_image"] = "Copia come immagine",
            ["menu_copy_svg"] = "Copia come SVG",
            ["dlg_save_as"] = "Salva con nome",
            ["dlg_image_files"] = "File immagine",
            ["err_title"] = "Errore",
            ["err_copy_image"] = "Errore nella copia dell'immagine negli appunti:",
            ["err_copy_svg"] = "Errore nella copia dell'SVG negli appunti:",
            ["err_no_text"] = "Inserisci del testo per generare il QR Code.",
            ["err_export"] = "Errore durante l'esportazione",
            ["err_open_url"] = "Impossibile aprire l'indirizzo.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "Email",
            ["fmt_phone"] = "Telefono",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Geolocalizzazione",
            ["fmt_contact"] = "Contatto",
            ["fmt_event"] = "Evento",
        },
        ["es"] = new Dictionary<string, string> {
            ["tip_save"] = "Guardar el código QR",
            ["tip_copy_image"] = "Copiar la imagen al portapapeles",
            ["tip_copy_svg"] = "Copiar el código SVG al portapapeles",
            ["tip_donate"] = "Invítame a un café",
            ["tip_help"] = "Ayuda",
            ["tip_language"] = "Idioma",
            ["tip_theme"] = "Cambiar tema",
            ["tip_mode"] = "Tipo de contenido: haz clic para cambiarlo",
            ["mode_auto"] = "Automático",
            ["mode_text"] = "Texto",
            ["invalid_content"] = "El texto no se ajusta al tipo de contenido elegido",
            ["wifi_ssid"] = "Nombre de la red",
            ["wifi_password"] = "Contraseña (vacía si la red es abierta)",
            ["wifi_security"] = "Seguridad",
            ["wifi_hidden"] = "Red oculta",
            ["tip_form"] = "Mostrar u ocultar el formulario",
            ["tip_form_none"] = "Este tipo de contenido no tiene formulario",
            ["mail_address"] = "Dirección de email",
            ["mail_subject"] = "Asunto",
            ["field_message"] = "Mensaje",
            ["field_phone"] = "Número de teléfono",
            ["field_intl_phone"] = "Número con prefijo internacional",
            ["contact_first"] = "Nombre",
            ["contact_last"] = "Apellidos",
            ["contact_phone"] = "Teléfono",
            ["contact_email"] = "Email",
            ["contact_org"] = "Empresa",
            ["contact_web"] = "Sitio web",
            ["event_title"] = "Título",
            ["event_location"] = "Lugar",
            ["event_description"] = "Descripción",
            ["event_all_day"] = "Todo el día",
            ["event_start"] = "Inicio",
            ["event_end"] = "Fin",
            ["help_intro"] = "Escribe o pega texto, un enlace, un email o un número: el código se actualiza mientras escribes. El tipo de contenido se detecta solo; para elegirlo tú, usa la barra inferior.",
            ["help_examples"] = "Ejemplos",
            ["help_guide"] = "Guía completa",
            ["ph_mail"] = "email;asunto;mensaje",
            ["ph_phone"] = "número de teléfono",
            ["ph_sms"] = "número;mensaje",
            ["ph_whatsapp"] = "+número internacional;mensaje",
            ["ph_geo"] = "latitud,longitud",
            ["ph_contact"] = "nombre;apellido;teléfono;email",
            ["ph_event"] = "título;descripción;lugar;inicio;fin",
            ["tip_repo"] = "Abrir el repositorio del proyecto",
            ["tip_fg"] = "Define el color de los píxeles",
            ["tip_bg"] = "Define el color de fondo",
            ["color_code"] = "Código",
            ["color_background"] = "Fondo",
            ["tip_text"] = "Introduce aquí el texto para el código QR",
            ["tip_picture"] = "Haz clic derecho en la imagen para ver las opciones",
            ["placeholder"] = "Introduce aquí el texto para el código QR",
            ["waiting"] = "Esperando entrada...",
            ["logo_set"] = "Añadir el logo",
            ["logo_remove"] = "Quitar el logo",
            ["menu_save_as"] = "Guardar como",
            ["menu_copy_image"] = "Copiar como imagen",
            ["menu_copy_svg"] = "Copiar como SVG",
            ["dlg_save_as"] = "Guardar como",
            ["dlg_image_files"] = "Archivos de imagen",
            ["err_title"] = "Error",
            ["err_copy_image"] = "Error al copiar la imagen al portapapeles:",
            ["err_copy_svg"] = "Error al copiar el SVG al portapapeles:",
            ["err_no_text"] = "Introduce un texto para generar el código QR.",
            ["err_export"] = "Error al exportar",
            ["err_open_url"] = "No se puede abrir la dirección.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "Correo",
            ["fmt_phone"] = "Teléfono",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Geolocalización",
            ["fmt_contact"] = "Contacto",
            ["fmt_event"] = "Evento",
        },
        ["fr"] = new Dictionary<string, string> {
            ["tip_save"] = "Enregistrer le QR Code",
            ["tip_copy_image"] = "Copier l'image dans le presse-papiers",
            ["tip_copy_svg"] = "Copier le code SVG dans le presse-papiers",
            ["tip_donate"] = "Offrez-moi un café",
            ["tip_help"] = "Aide",
            ["tip_language"] = "Langue",
            ["tip_theme"] = "Changer de thème",
            ["tip_mode"] = "Type de contenu : cliquez pour le modifier",
            ["mode_auto"] = "Automatique",
            ["mode_text"] = "Texte",
            ["invalid_content"] = "Le texte ne correspond pas au type de contenu choisi",
            ["wifi_ssid"] = "Nom du réseau",
            ["wifi_password"] = "Mot de passe (vide pour un réseau ouvert)",
            ["wifi_security"] = "Sécurité",
            ["wifi_hidden"] = "Réseau masqué",
            ["tip_form"] = "Afficher ou masquer le formulaire",
            ["tip_form_none"] = "Ce type de contenu n'a pas de formulaire",
            ["mail_address"] = "Adresse e-mail",
            ["mail_subject"] = "Objet",
            ["field_message"] = "Message",
            ["field_phone"] = "Numéro de téléphone",
            ["field_intl_phone"] = "Numéro avec indicatif international",
            ["contact_first"] = "Prénom",
            ["contact_last"] = "Nom",
            ["contact_phone"] = "Téléphone",
            ["contact_email"] = "E-mail",
            ["contact_org"] = "Entreprise",
            ["contact_web"] = "Site web",
            ["event_title"] = "Titre",
            ["event_location"] = "Lieu",
            ["event_description"] = "Description",
            ["event_all_day"] = "Toute la journée",
            ["event_start"] = "Début",
            ["event_end"] = "Fin",
            ["help_intro"] = "Saisissez ou collez du texte, un lien, un e-mail ou un numéro : le code se met à jour pendant la saisie. Le type de contenu est détecté automatiquement ; pour le choisir vous-même, utilisez la barre du bas.",
            ["help_examples"] = "Exemples",
            ["help_guide"] = "Guide complet",
            ["ph_mail"] = "e-mail;objet;message",
            ["ph_phone"] = "numéro de téléphone",
            ["ph_sms"] = "numéro;message",
            ["ph_whatsapp"] = "+numéro international;message",
            ["ph_geo"] = "latitude,longitude",
            ["ph_contact"] = "prénom;nom;téléphone;e-mail",
            ["ph_event"] = "titre;description;lieu;début;fin",
            ["tip_repo"] = "Ouvrir le dépôt du projet",
            ["tip_fg"] = "Définit la couleur des pixels",
            ["tip_bg"] = "Définit la couleur d'arrière-plan",
            ["color_code"] = "Code",
            ["color_background"] = "Fond",
            ["tip_text"] = "Saisissez ici le texte du QR Code",
            ["tip_picture"] = "Clic droit sur l'image pour les options",
            ["placeholder"] = "Saisissez ici le texte du QR Code",
            ["waiting"] = "En attente de saisie...",
            ["logo_set"] = "Ajouter un logo",
            ["logo_remove"] = "Retirer le logo",
            ["menu_save_as"] = "Enregistrer sous",
            ["menu_copy_image"] = "Copier comme image",
            ["menu_copy_svg"] = "Copier comme SVG",
            ["dlg_save_as"] = "Enregistrer sous",
            ["dlg_image_files"] = "Fichiers image",
            ["err_title"] = "Erreur",
            ["err_copy_image"] = "Erreur lors de la copie de l'image dans le presse-papiers :",
            ["err_copy_svg"] = "Erreur lors de la copie du SVG dans le presse-papiers :",
            ["err_no_text"] = "Saisissez un texte pour générer le QR Code.",
            ["err_export"] = "Erreur lors de l'exportation",
            ["err_open_url"] = "Impossible d'ouvrir l'adresse.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "E-mail",
            ["fmt_phone"] = "Téléphone",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Géolocalisation",
            ["fmt_contact"] = "Contact",
            ["fmt_event"] = "Événement",
        },
        ["de"] = new Dictionary<string, string> {
            ["tip_save"] = "QR-Code speichern",
            ["tip_copy_image"] = "Bild in die Zwischenablage kopieren",
            ["tip_copy_svg"] = "SVG-Code in die Zwischenablage kopieren",
            ["tip_donate"] = "Spendiere mir einen Kaffee",
            ["tip_help"] = "Hilfe",
            ["tip_language"] = "Sprache",
            ["tip_theme"] = "Design wechseln",
            ["tip_mode"] = "Inhaltstyp: zum Ändern klicken",
            ["mode_auto"] = "Automatisch",
            ["mode_text"] = "Text",
            ["invalid_content"] = "Der Text passt nicht zum gewählten Inhaltstyp",
            ["wifi_ssid"] = "Netzwerkname",
            ["wifi_password"] = "Passwort (leer bei offenem Netzwerk)",
            ["wifi_security"] = "Sicherheit",
            ["wifi_hidden"] = "Verstecktes Netzwerk",
            ["tip_form"] = "Formular ein- oder ausblenden",
            ["tip_form_none"] = "Für diesen Inhaltstyp gibt es kein Formular",
            ["mail_address"] = "E-Mail-Adresse",
            ["mail_subject"] = "Betreff",
            ["field_message"] = "Nachricht",
            ["field_phone"] = "Telefonnummer",
            ["field_intl_phone"] = "Nummer mit Ländervorwahl",
            ["contact_first"] = "Vorname",
            ["contact_last"] = "Nachname",
            ["contact_phone"] = "Telefon",
            ["contact_email"] = "E-Mail",
            ["contact_org"] = "Firma",
            ["contact_web"] = "Website",
            ["event_title"] = "Titel",
            ["event_location"] = "Ort",
            ["event_description"] = "Beschreibung",
            ["event_all_day"] = "Ganztägig",
            ["event_start"] = "Beginn",
            ["event_end"] = "Ende",
            ["help_intro"] = "Text, Link, E-Mail oder Nummer eingeben oder einfügen: Der Code aktualisiert sich beim Tippen. Der Inhaltstyp wird automatisch erkannt; um ihn selbst zu wählen, nutze die Leiste unten.",
            ["help_examples"] = "Beispiele",
            ["help_guide"] = "Vollständige Anleitung",
            ["ph_mail"] = "E-Mail;Betreff;Nachricht",
            ["ph_phone"] = "Telefonnummer",
            ["ph_sms"] = "Nummer;Nachricht",
            ["ph_whatsapp"] = "+internationale Nummer;Nachricht",
            ["ph_geo"] = "Breitengrad,Längengrad",
            ["ph_contact"] = "Vorname;Nachname;Telefon;E-Mail",
            ["ph_event"] = "Titel;Beschreibung;Ort;Beginn;Ende",
            ["tip_repo"] = "Projekt-Repository öffnen",
            ["tip_fg"] = "Legt die Pixelfarbe fest",
            ["tip_bg"] = "Legt die Hintergrundfarbe fest",
            ["color_code"] = "Code",
            ["color_background"] = "Hintergrund",
            ["tip_text"] = "Hier den Text für den QR-Code eingeben",
            ["tip_picture"] = "Rechtsklick auf das Bild für Optionen",
            ["placeholder"] = "Hier den Text für den QR-Code eingeben",
            ["waiting"] = "Warte auf Eingabe...",
            ["logo_set"] = "Logo hinzufügen",
            ["logo_remove"] = "Logo entfernen",
            ["menu_save_as"] = "Speichern unter",
            ["menu_copy_image"] = "Als Bild kopieren",
            ["menu_copy_svg"] = "Als SVG kopieren",
            ["dlg_save_as"] = "Speichern unter",
            ["dlg_image_files"] = "Bilddateien",
            ["err_title"] = "Fehler",
            ["err_copy_image"] = "Fehler beim Kopieren des Bildes in die Zwischenablage:",
            ["err_copy_svg"] = "Fehler beim Kopieren des SVG in die Zwischenablage:",
            ["err_no_text"] = "Gib einen Text ein, um den QR-Code zu erzeugen.",
            ["err_export"] = "Fehler beim Exportieren",
            ["err_open_url"] = "Die Adresse kann nicht geöffnet werden.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "E-Mail",
            ["fmt_phone"] = "Telefon",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WLAN",
            ["fmt_geo"] = "Geolokalisierung",
            ["fmt_contact"] = "Kontakt",
            ["fmt_event"] = "Termin",
        },
        ["pt"] = new Dictionary<string, string> {
            ["tip_save"] = "Guardar o código QR",
            ["tip_copy_image"] = "Copiar a imagem para a área de transferência",
            ["tip_copy_svg"] = "Copiar o código SVG para a área de transferência",
            ["tip_donate"] = "Paga-me um café",
            ["tip_help"] = "Ajuda",
            ["tip_language"] = "Idioma",
            ["tip_theme"] = "Mudar tema",
            ["tip_mode"] = "Tipo de conteúdo: clique para alterar",
            ["mode_auto"] = "Automático",
            ["mode_text"] = "Texto",
            ["invalid_content"] = "O texto não corresponde ao tipo de conteúdo escolhido",
            ["wifi_ssid"] = "Nome da rede",
            ["wifi_password"] = "Palavra-passe (vazia se a rede for aberta)",
            ["wifi_security"] = "Segurança",
            ["wifi_hidden"] = "Rede oculta",
            ["tip_form"] = "Mostrar ou ocultar o formulário",
            ["tip_form_none"] = "Este tipo de conteúdo não tem formulário",
            ["mail_address"] = "Endereço de email",
            ["mail_subject"] = "Assunto",
            ["field_message"] = "Mensagem",
            ["field_phone"] = "Número de telefone",
            ["field_intl_phone"] = "Número com indicativo internacional",
            ["contact_first"] = "Nome",
            ["contact_last"] = "Apelido",
            ["contact_phone"] = "Telefone",
            ["contact_email"] = "Email",
            ["contact_org"] = "Empresa",
            ["contact_web"] = "Site",
            ["event_title"] = "Título",
            ["event_location"] = "Local",
            ["event_description"] = "Descrição",
            ["event_all_day"] = "Dia inteiro",
            ["event_start"] = "Início",
            ["event_end"] = "Fim",
            ["help_intro"] = "Escreva ou cole texto, uma ligação, um email ou um número: o código atualiza-se enquanto escreve. O tipo de conteúdo é detetado automaticamente; para o escolher, use a barra em baixo.",
            ["help_examples"] = "Exemplos",
            ["help_guide"] = "Guia completo",
            ["ph_mail"] = "email;assunto;mensagem",
            ["ph_phone"] = "número de telefone",
            ["ph_sms"] = "número;mensagem",
            ["ph_whatsapp"] = "+número internacional;mensagem",
            ["ph_geo"] = "latitude,longitude",
            ["ph_contact"] = "nome;apelido;telefone;email",
            ["ph_event"] = "título;descrição;local;início;fim",
            ["tip_repo"] = "Abrir o repositório do projeto",
            ["tip_fg"] = "Define a cor dos pixels",
            ["tip_bg"] = "Define a cor de fundo",
            ["color_code"] = "Código",
            ["color_background"] = "Fundo",
            ["tip_text"] = "Introduza aqui o texto para o código QR",
            ["tip_picture"] = "Clique com o botão direito na imagem para ver as opções",
            ["placeholder"] = "Introduza aqui o texto para o código QR",
            ["waiting"] = "À espera de entrada...",
            ["logo_set"] = "Adicionar o logótipo",
            ["logo_remove"] = "Remover o logótipo",
            ["menu_save_as"] = "Guardar como",
            ["menu_copy_image"] = "Copiar como imagem",
            ["menu_copy_svg"] = "Copiar como SVG",
            ["dlg_save_as"] = "Guardar como",
            ["dlg_image_files"] = "Ficheiros de imagem",
            ["err_title"] = "Erro",
            ["err_copy_image"] = "Erro ao copiar a imagem para a área de transferência:",
            ["err_copy_svg"] = "Erro ao copiar o SVG para a área de transferência:",
            ["err_no_text"] = "Introduza um texto para gerar o código QR.",
            ["err_export"] = "Erro ao exportar",
            ["err_open_url"] = "Não é possível abrir o endereço.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "Email",
            ["fmt_phone"] = "Telefone",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Geolocalização",
            ["fmt_contact"] = "Contacto",
            ["fmt_event"] = "Evento",
        },
        ["ru"] = new Dictionary<string, string> {
            ["tip_save"] = "Сохранить QR-код",
            ["tip_copy_image"] = "Копировать изображение в буфер обмена",
            ["tip_copy_svg"] = "Копировать код SVG в буфер обмена",
            ["tip_donate"] = "Купить мне кофе",
            ["tip_help"] = "Справка",
            ["tip_language"] = "Язык",
            ["tip_theme"] = "Сменить тему",
            ["tip_mode"] = "Тип содержимого: нажмите, чтобы изменить",
            ["mode_auto"] = "Автоматически",
            ["mode_text"] = "Текст",
            ["invalid_content"] = "Текст не подходит для выбранного типа содержимого",
            ["wifi_ssid"] = "Имя сети",
            ["wifi_password"] = "Пароль (пусто для открытой сети)",
            ["wifi_security"] = "Защита",
            ["wifi_hidden"] = "Скрытая сеть",
            ["tip_form"] = "Показать или скрыть форму",
            ["tip_form_none"] = "Для этого типа содержимого нет формы",
            ["mail_address"] = "Адрес email",
            ["mail_subject"] = "Тема",
            ["field_message"] = "Сообщение",
            ["field_phone"] = "Номер телефона",
            ["field_intl_phone"] = "Номер с кодом страны",
            ["contact_first"] = "Имя",
            ["contact_last"] = "Фамилия",
            ["contact_phone"] = "Телефон",
            ["contact_email"] = "Email",
            ["contact_org"] = "Компания",
            ["contact_web"] = "Веб-сайт",
            ["event_title"] = "Название",
            ["event_location"] = "Место",
            ["event_description"] = "Описание",
            ["event_all_day"] = "Весь день",
            ["event_start"] = "Начало",
            ["event_end"] = "Конец",
            ["help_intro"] = "Введите или вставьте текст, ссылку, email или номер: код обновляется по мере ввода. Тип содержимого определяется автоматически; чтобы выбрать его вручную, используйте нижнюю панель.",
            ["help_examples"] = "Примеры",
            ["help_guide"] = "Полное руководство",
            ["ph_mail"] = "email;тема;сообщение",
            ["ph_phone"] = "номер телефона",
            ["ph_sms"] = "номер;сообщение",
            ["ph_whatsapp"] = "+международный номер;сообщение",
            ["ph_geo"] = "широта,долгота",
            ["ph_contact"] = "имя;фамилия;телефон;email",
            ["ph_event"] = "название;описание;место;начало;конец",
            ["tip_repo"] = "Открыть репозиторий проекта",
            ["tip_fg"] = "Задаёт цвет пикселей",
            ["tip_bg"] = "Задаёт цвет фона",
            ["color_code"] = "Код",
            ["color_background"] = "Фон",
            ["tip_text"] = "Введите здесь текст для QR-кода",
            ["tip_picture"] = "Щёлкните правой кнопкой по изображению для параметров",
            ["placeholder"] = "Введите здесь текст для QR-кода",
            ["waiting"] = "Ожидание ввода...",
            ["logo_set"] = "Добавить логотип",
            ["logo_remove"] = "Убрать логотип",
            ["menu_save_as"] = "Сохранить как",
            ["menu_copy_image"] = "Копировать как изображение",
            ["menu_copy_svg"] = "Копировать как SVG",
            ["dlg_save_as"] = "Сохранить как",
            ["dlg_image_files"] = "Файлы изображений",
            ["err_title"] = "Ошибка",
            ["err_copy_image"] = "Ошибка при копировании изображения в буфер обмена:",
            ["err_copy_svg"] = "Ошибка при копировании SVG в буфер обмена:",
            ["err_no_text"] = "Введите текст для создания QR-кода.",
            ["err_export"] = "Ошибка при экспорте",
            ["err_open_url"] = "Не удалось открыть адрес.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "Эл. почта",
            ["fmt_phone"] = "Телефон",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "Геолокация",
            ["fmt_contact"] = "Контакт",
            ["fmt_event"] = "Событие",
        },
        ["zh"] = new Dictionary<string, string> {
            ["tip_save"] = "保存二维码",
            ["tip_copy_image"] = "复制图片到剪贴板",
            ["tip_copy_svg"] = "复制 SVG 代码到剪贴板",
            ["tip_donate"] = "请我喝杯咖啡",
            ["tip_help"] = "帮助",
            ["tip_language"] = "语言",
            ["tip_theme"] = "切换主题",
            ["tip_mode"] = "内容类型：点击更改",
            ["mode_auto"] = "自动",
            ["mode_text"] = "文本",
            ["invalid_content"] = "文本不符合所选的内容类型",
            ["wifi_ssid"] = "网络名称",
            ["wifi_password"] = "密码（开放网络留空）",
            ["wifi_security"] = "安全类型",
            ["wifi_hidden"] = "隐藏网络",
            ["tip_form"] = "显示或隐藏表单",
            ["tip_form_none"] = "此内容类型没有表单",
            ["mail_address"] = "邮箱地址",
            ["mail_subject"] = "主题",
            ["field_message"] = "内容",
            ["field_phone"] = "电话号码",
            ["field_intl_phone"] = "带国家区号的号码",
            ["contact_first"] = "名",
            ["contact_last"] = "姓",
            ["contact_phone"] = "电话",
            ["contact_email"] = "邮箱",
            ["contact_org"] = "公司",
            ["contact_web"] = "网站",
            ["event_title"] = "标题",
            ["event_location"] = "地点",
            ["event_description"] = "描述",
            ["event_all_day"] = "全天",
            ["event_start"] = "开始",
            ["event_end"] = "结束",
            ["help_intro"] = "输入或粘贴文本、链接、邮箱或号码，二维码会随输入实时更新。内容类型会自动识别；如需手动选择，请使用底部栏。",
            ["help_examples"] = "示例",
            ["help_guide"] = "完整指南",
            ["ph_mail"] = "邮箱;主题;内容",
            ["ph_phone"] = "电话号码",
            ["ph_sms"] = "号码;内容",
            ["ph_whatsapp"] = "+国际号码;内容",
            ["ph_geo"] = "纬度,经度",
            ["ph_contact"] = "名;姓;电话;邮箱",
            ["ph_event"] = "标题;描述;地点;开始;结束",
            ["tip_repo"] = "打开项目仓库",
            ["tip_fg"] = "设置像素颜色",
            ["tip_bg"] = "设置背景颜色",
            ["color_code"] = "码",
            ["color_background"] = "背景",
            ["tip_text"] = "在此输入二维码内容",
            ["tip_picture"] = "右键点击图片查看选项",
            ["placeholder"] = "在此输入二维码内容",
            ["waiting"] = "等待输入...",
            ["logo_set"] = "添加标志",
            ["logo_remove"] = "移除标志",
            ["menu_save_as"] = "另存为",
            ["menu_copy_image"] = "复制为图片",
            ["menu_copy_svg"] = "复制为 SVG",
            ["dlg_save_as"] = "另存为",
            ["dlg_image_files"] = "图片文件",
            ["err_title"] = "错误",
            ["err_copy_image"] = "复制图片到剪贴板时出错：",
            ["err_copy_svg"] = "复制 SVG 到剪贴板时出错：",
            ["err_no_text"] = "请输入文本以生成二维码。",
            ["err_export"] = "导出时出错",
            ["err_open_url"] = "无法打开该网址。",
            ["fmt_url"] = "网址",
            ["fmt_mail"] = "电子邮件",
            ["fmt_phone"] = "电话",
            ["fmt_sms"] = "短信",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "地理位置",
            ["fmt_contact"] = "联系人",
            ["fmt_event"] = "日程",
        },
        ["ja"] = new Dictionary<string, string> {
            ["tip_save"] = "QRコードを保存",
            ["tip_copy_image"] = "画像をクリップボードにコピー",
            ["tip_copy_svg"] = "SVGコードをクリップボードにコピー",
            ["tip_donate"] = "コーヒーをおごる",
            ["tip_help"] = "ヘルプ",
            ["tip_language"] = "言語",
            ["tip_theme"] = "テーマを切り替え",
            ["tip_mode"] = "コンテンツの種類：クリックして変更",
            ["mode_auto"] = "自動",
            ["mode_text"] = "テキスト",
            ["invalid_content"] = "テキストが選択した種類に合いません",
            ["wifi_ssid"] = "ネットワーク名",
            ["wifi_password"] = "パスワード（オープンネットワークは空欄）",
            ["wifi_security"] = "セキュリティ",
            ["wifi_hidden"] = "非公開ネットワーク",
            ["tip_form"] = "フォームの表示/非表示",
            ["tip_form_none"] = "この種類にはフォームがありません",
            ["mail_address"] = "メールアドレス",
            ["mail_subject"] = "件名",
            ["field_message"] = "メッセージ",
            ["field_phone"] = "電話番号",
            ["field_intl_phone"] = "国番号付きの番号",
            ["contact_first"] = "名",
            ["contact_last"] = "姓",
            ["contact_phone"] = "電話",
            ["contact_email"] = "メール",
            ["contact_org"] = "会社",
            ["contact_web"] = "ウェブサイト",
            ["event_title"] = "タイトル",
            ["event_location"] = "場所",
            ["event_description"] = "説明",
            ["event_all_day"] = "終日",
            ["event_start"] = "開始",
            ["event_end"] = "終了",
            ["help_intro"] = "テキスト、リンク、メールアドレス、番号を入力または貼り付けると、コードが入力に合わせて更新されます。種類は自動で判別されます。自分で選ぶ場合は下のバーを使ってください。",
            ["help_examples"] = "例",
            ["help_guide"] = "詳しいガイド",
            ["ph_mail"] = "メール;件名;本文",
            ["ph_phone"] = "電話番号",
            ["ph_sms"] = "番号;メッセージ",
            ["ph_whatsapp"] = "+国際番号;メッセージ",
            ["ph_geo"] = "緯度,経度",
            ["ph_contact"] = "名;姓;電話;メール",
            ["ph_event"] = "タイトル;説明;場所;開始;終了",
            ["tip_repo"] = "プロジェクトのリポジトリを開く",
            ["tip_fg"] = "ピクセルの色を設定します",
            ["tip_bg"] = "背景の色を設定します",
            ["color_code"] = "コード",
            ["color_background"] = "背景",
            ["tip_text"] = "QRコードにするテキストをここに入力",
            ["tip_picture"] = "画像を右クリックするとオプションが表示されます",
            ["placeholder"] = "QRコードにするテキストをここに入力",
            ["waiting"] = "入力待ちです...",
            ["logo_set"] = "ロゴを追加",
            ["logo_remove"] = "ロゴを削除",
            ["menu_save_as"] = "名前を付けて保存",
            ["menu_copy_image"] = "画像としてコピー",
            ["menu_copy_svg"] = "SVGとしてコピー",
            ["dlg_save_as"] = "名前を付けて保存",
            ["dlg_image_files"] = "画像ファイル",
            ["err_title"] = "エラー",
            ["err_copy_image"] = "画像をクリップボードにコピーする際のエラー:",
            ["err_copy_svg"] = "SVGをクリップボードにコピーする際のエラー:",
            ["err_no_text"] = "QRコードを生成するテキストを入力してください。",
            ["err_export"] = "エクスポート中のエラー",
            ["err_open_url"] = "URLを開けません。",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "メール",
            ["fmt_phone"] = "電話",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "位置情報",
            ["fmt_contact"] = "連絡先",
            ["fmt_event"] = "予定",
        },
        ["ko"] = new Dictionary<string, string> {
            ["tip_save"] = "QR 코드 저장",
            ["tip_copy_image"] = "이미지를 클립보드에 복사",
            ["tip_copy_svg"] = "SVG 코드를 클립보드에 복사",
            ["tip_donate"] = "커피 사주기",
            ["tip_help"] = "도움말",
            ["tip_language"] = "언어",
            ["tip_theme"] = "테마 전환",
            ["tip_mode"] = "콘텐츠 유형: 클릭하여 변경",
            ["mode_auto"] = "자동",
            ["mode_text"] = "텍스트",
            ["invalid_content"] = "텍스트가 선택한 콘텐츠 유형과 맞지 않습니다",
            ["wifi_ssid"] = "네트워크 이름",
            ["wifi_password"] = "비밀번호 (개방형 네트워크는 비워 두기)",
            ["wifi_security"] = "보안",
            ["wifi_hidden"] = "숨겨진 네트워크",
            ["tip_form"] = "양식 표시/숨기기",
            ["tip_form_none"] = "이 콘텐츠 유형에는 양식이 없습니다",
            ["mail_address"] = "이메일 주소",
            ["mail_subject"] = "제목",
            ["field_message"] = "메시지",
            ["field_phone"] = "전화번호",
            ["field_intl_phone"] = "국가 번호를 포함한 번호",
            ["contact_first"] = "이름",
            ["contact_last"] = "성",
            ["contact_phone"] = "전화",
            ["contact_email"] = "이메일",
            ["contact_org"] = "회사",
            ["contact_web"] = "웹사이트",
            ["event_title"] = "제목",
            ["event_location"] = "장소",
            ["event_description"] = "설명",
            ["event_all_day"] = "종일",
            ["event_start"] = "시작",
            ["event_end"] = "종료",
            ["help_intro"] = "텍스트, 링크, 이메일 또는 번호를 입력하거나 붙여 넣으면 입력하는 동안 코드가 업데이트됩니다. 콘텐츠 유형은 자동으로 인식되며, 직접 선택하려면 아래쪽 막대를 사용하세요.",
            ["help_examples"] = "예시",
            ["help_guide"] = "전체 가이드",
            ["ph_mail"] = "이메일;제목;내용",
            ["ph_phone"] = "전화번호",
            ["ph_sms"] = "번호;메시지",
            ["ph_whatsapp"] = "+국제 번호;메시지",
            ["ph_geo"] = "위도,경도",
            ["ph_contact"] = "이름;성;전화;이메일",
            ["ph_event"] = "제목;설명;장소;시작;종료",
            ["tip_repo"] = "프로젝트 저장소 열기",
            ["tip_fg"] = "픽셀 색상을 설정합니다",
            ["tip_bg"] = "배경 색상을 설정합니다",
            ["color_code"] = "코드",
            ["color_background"] = "배경",
            ["tip_text"] = "QR 코드에 넣을 텍스트를 여기에 입력",
            ["tip_picture"] = "이미지를 오른쪽 클릭하면 옵션이 표시됩니다",
            ["placeholder"] = "QR 코드에 넣을 텍스트를 여기에 입력",
            ["waiting"] = "입력을 기다리는 중...",
            ["logo_set"] = "로고 추가",
            ["logo_remove"] = "로고 제거",
            ["menu_save_as"] = "다른 이름으로 저장",
            ["menu_copy_image"] = "이미지로 복사",
            ["menu_copy_svg"] = "SVG로 복사",
            ["dlg_save_as"] = "다른 이름으로 저장",
            ["dlg_image_files"] = "이미지 파일",
            ["err_title"] = "오류",
            ["err_copy_image"] = "이미지를 클립보드에 복사하는 중 오류:",
            ["err_copy_svg"] = "SVG를 클립보드에 복사하는 중 오류:",
            ["err_no_text"] = "QR 코드를 생성할 텍스트를 입력하세요.",
            ["err_export"] = "내보내는 중 오류",
            ["err_open_url"] = "주소를 열 수 없습니다.",
            ["fmt_url"] = "URL",
            ["fmt_mail"] = "이메일",
            ["fmt_phone"] = "전화",
            ["fmt_sms"] = "SMS",
            ["fmt_whatsapp"] = "WhatsApp",
            ["fmt_wifi"] = "WiFi",
            ["fmt_geo"] = "위치",
            ["fmt_contact"] = "연락처",
            ["fmt_event"] = "일정",
        }
    };

    #endregion

    #region Properties

    public static string CurrentLanguage { get; private set; } = DefaultLanguage;

    public static IReadOnlyDictionary<string, string> LanguageNames => languageNames;

    #endregion

    #region Public Methods

    /// <summary>
    ///     Imposta la lingua iniziale: quella salvata dall'utente, altrimenti quella di Windows.
    /// </summary>
    public static void Initialize()
    {
        string? saved = LoadSavedLanguage();

        CurrentLanguage = saved ?? DetectSystemLanguage();
    }

    public static void SetLanguage(string language)
    {
        CurrentLanguage = strings.ContainsKey(language) ? language : DefaultLanguage;
        SaveLanguage(CurrentLanguage);
    }

    /// <summary>
    ///     Restituisce la stringa localizzata, con fallback all'inglese e infine alla chiave stessa.
    /// </summary>
    public static string T(string key)
    {
        if (strings.TryGetValue(CurrentLanguage, out Dictionary<string, string>? table) &&
            table.TryGetValue(key, out string? value)) {
            return value;
        }

        if (strings[DefaultLanguage].TryGetValue(key, out string? fallback)) {
            return fallback;
        }

        return key;
    }

    #endregion

    #region Private Methods

    private static string DetectSystemLanguage()
    {
        try {
            string code = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            return strings.ContainsKey(code) ? code : DefaultLanguage;
        } catch {
            return DefaultLanguage;
        }
    }

    private static string? LoadSavedLanguage()
    {
        string? code = UserSettings.Get(SettingsKey)?.Trim().ToLowerInvariant();

        return code != null && strings.ContainsKey(code) ? code : null;
    }

    private static void SaveLanguage(string language)
    {
        UserSettings.Set(SettingsKey, language);
    }

    #endregion
}